### ISSUE TITLE
setup refers to non-existant URLs

### ISSUE THREAD

**Issue by rmustacc** [joyent/sdc-headnode#10]
The headnode's setup refers to two URLs on docs.joyent.com (
http://docs.joyent.com/sdc7/overview-of-smartdatacenter-7) and ( http://docs.joyent.com/sdc7/installing-sdc7) which no longer exist. These should be redirected to new URLs. In fact, the same problem can been on https://docs.joyent.com/private-cloud/install#triton-installer. We should update these URLs to their new homes.

@qdzlug do you know off hand what the right replacement URLs for these should be?

**Comment by misterbisson** [comment]
@rmustacc 

- http://docs.joyent.com/sdc7/overview-of-smartdatacenter-7 -> https://docs.joyent.com/private-cloud

- http://docs.joyent.com/sdc7/installing-sdc7 -> https://docs.joyent.com/private-cloud/install

I confirmed those from the contents in Wayback: 

- http://web.archive.org/web/*/https://docs.joyent.com/sdc7/overview-of-smartdatacenter-7

- http://web.archive.org/web/*/https://docs.joyent.com/sdc7/installing-sdc7

**Comment by bahamat** [comment]
Fixed in TRITON-265 (1d58b6c2c)
