### ISSUE TITLE
fail to make coal on MAC 10.11

### ISSUE THREAD

**Issue by freddyfu** [joyent/sdc-headnode#15]
I made a git clone from it clone https://github.com/joyent/sdc-headnode.git and make coal failed as this:

Fus-MacBook-Pro:sdc-headnode fuqiang$ make coal
npm install
touch 0-npm-stamp
mkdir -p cache
mkdir -p log
./bin/checker
if [ -z ${NO_DOWNLOAD} ]; then \
		./bin/downloader -d -w "log/artefacts.json"; \
	else \
		true; \
	fi

/Users/fuqiang/sdc/sdc-headnode/node_modules/smartdc-auth/node_modules/assert-plus/assert.js:22
    throw new assert.AssertionError({
    ^
AssertionError: options.keyId (string) is required
    at Object.cliSigner (/Users/fuqiang/sdc/sdc-headnode/node_modules/smartdc-auth/lib/index.js:108:13)
    at create_manta_client (/Users/fuqiang/sdc/sdc-headnode/buildtools/novus/cmd/downloader.js:461:25)
    at /Users/fuqiang/sdc/sdc-headnode/buildtools/novus/cmd/downloader.js:492:15
    at /Users/fuqiang/sdc/sdc-headnode/buildtools/novus/lib/buildspec.js:269:4
    at next (/Users/fuqiang/sdc/sdc-headnode/node_modules/vasync/lib/vasync.js:201:4)
    at /Users/fuqiang/sdc/sdc-headnode/buildtools/novus/lib/buildspec.js:139:3
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
make: *** [download] Error 1

my setup info are these with MAC OS 10.11
Fus-MacBook-Pro:sdc-headnode fuqiang$ node -v
v7.5.0
Fus-MacBook-Pro:sdc-headnode fuqiang$ npm -v
4.1.2
Fus-MacBook-Pro:sdc-headnode fuqiang$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

are there any ways to fix this issue and appreciate it if you give me some input?

thanks
freddy

**Comment by bahamat** [comment]
Building is only supported on SmartOS.
