### ISSUE TITLE
rpc/bind enabled by default

### ISSUE THREAD

**Issue by alaslums** [joyent/sdc-headnode#18]
On a fresh install of Triton (joyent_20180215T033410Z), rpc/bind is enabled and listening on all interfaces, including external0:

```
[root@headnode (eu-west-1) ~]# netstat -an | grep LIST
127.0.0.1.8080             *.*                0      0 1048576      0 LISTEN
10.20.0.1.5309             *.*                0      0 1048576      0 LISTEN
10.20.0.1.9163             *.*                0      0 1048576      0 LISTEN
      *.111                *.*                0      0 1048576      0 LISTEN
      *.111                *.*                0      0 1048576      0 LISTEN
      *.22                 *.*                0      0 1048576      0 LISTEN
10.20.0.1.2021             *.*                0      0 1048576      0 LISTEN
127.0.0.1.25               *.*                0      0 1048576      0 LISTEN
127.0.0.1.587              *.*                0      0 1048576      0 LISTEN
127.0.0.1.4307             *.*                0      0 1048576      0 LISTEN
      *.111                             *.*                             0      0 1048576      0 LISTEN
      *.22                              *.*                             0      0 1048576      0 LISTEN
::1.25                                  *.*                             0      0 1048576      0 LISTEN

[root@headnode (eu-west-1) ~]# svcs -a | grep rpc/bind
online         Mar_06   svc:/network/rpc/bind:default
```

I'm guessing this is not supposed to be the case.

**Comment by alaslums** [comment]
Actually, rpc/bind is required for fmd. Interestingly, the rpc/bind SMF definition has a config section with "local_only" set to "true", I guess this definition doesn't restrict which IP it listens on.

**Comment by jclulow** [comment]
Yes, FMA uses a bunch of local RPC services.

I believe `rpcbind` drops traffic based on whether it's actually from processes on the local machine or not.  For more details, I would look at the [`localxprt()`](https://github.com/joyent/illumos-joyent/blob/master/usr/src/cmd/rpcbind/pmap_svc.c#L340-L371) function, as well as the places where it gets used if `local_only` is set to `B_TRUE` (based on the SMF property).

According to the manual page (`rpcbind(1M)`):

```
       The following SMF property is used to allow or disallow access to
       rpcbind by remote clients:

         config/local_only = true

       The default value, true, shown above, disallows remote access; a value
       of false allows remove access. See EXAMPLES.
```

**Comment by jasonbking** [comment]
That is correct -- the problem is if other RPC processes use the hostname and try to connect to an IP configured on a non-loopback interface (instead of loopback), even for local stuff, things can break (which is why local_only works the way it does).
