### ISSUE TITLE
AdminUI admin password not set from answers.json

### ISSUE THREAD

**Issue by andrewbates09** [joyent/sdc-headnode#9]
### The Issue

During installation, the AdminUI password seems to be statically set, rather than being set from the answers.json configuration file.

Following the examples from the [joyent blog](https://www.joyent.com/blog/spin-up-a-docker-dev-test-environment-in-60-minutes-or-less) and [github blob](https://github.com/joyent/sdc-headnode/blob/master/answers.json.tmpl.external) the following doesn't set a password via the answers.json

``` json
{
    "admin_password": "admpassword1&",
    "api_password": "apipassword1&",
}
```
#### Temporary Workaround

Find the AdminUI admin UUID

```
[root@headnode (triton) ~]# sdc-useradm search admin
UUID                                  LOGIN  EMAIL             CREATED
930896af-bf8c-48d4-885c-6573a94b1853  admin  adm@example.com  2015-11-13
```

Reset the account password

```
sdc-ufds modify --dn 'uuid=930896af-bf8c-48d4-885c-6573a94b1853, ou=users, o=smartdc' --attribute userpassword --type replace --value 'admpassword1&'
```

**Comment by rmorano** [comment]
just a typo in "Reset the account password" comand

sdc-ufds modify --dn 'uuid=930896af-bf8c-48d4-885c-6573a94b1853, ou=users, o=smartdc' --attribute userpassword --type replace --value 'admpassword1&'

**Comment by andrewbates09** [comment]
@rmorano egads! Good catch; fixed.

**Comment by KrisShannon** [comment]
This might be related to HEAD-2279 (Special shell characters in admin password cause setup to fail) a fix for which was committed on Dec 12.
